### PR TITLE
Updated application to Rails 4.2

### PR DESCRIPTION
**Pull request by jlindley**
Important: This will break compatibility with Ruby 1.8.7 as it is not compatible with Ruby <1.9.3

Hold for approval on this ticket: https://tickets.engineyard.com/issue/Discuss-466 [ we just included the secret since the app is fully world-accessible and writeable in any case, so session attacks are harmless ]

Updated gems to Rails 4.2.0 compatibility

Fixed jq-tabs asset_path references

Updated tests to new naming conventions

Updated/added files for Rails 4.2

Updated app code for Rails 4.2

### CODE REVIEW

**Comment by slack** [comment]
This ready to go Jim?

**Comment by jlindley** [comment]
The original ticket said to hold this for https://tickets.engineyard.com/issue/Discuss-466

So the code is ready and I'm happy to merge but I don't know if it's tsill on hold

**Comment by jlindley** [comment]
I re-reviewed, and https://github.com/engineyard/todo/pull/19/files#diff-c44d4424e72cd1a2291ee1e96f1d86baR22 the key won't be set if a trial customer boots the todo app with these changes in production mode, their deploy will fail and a way they can't really fix.

I've added a commit to provide the production secret. This isn't very secure but this is just a demo app, and the app is world-write/readable anyways so session security does nothing to prevent anything in this app.

**Comment by jlindley** [comment]
This branch seems to work as it is now in cloud w/out manual intervention to setup.

**Pull request merged**
